interface ImportMeta {
  env: {
    VITE_MAINNET_PDP_VERIFIER: string
    VITE_MAINNET_PDP_SERVICE: string
    VITE_CALIBRATION_PDP_VERIFIER: string
    VITE_CALIBRATION_PDP_SERVICE: string
    VITE_GOLDSKY_PROJECT_ID: string
    VITE_GOLDSKY_PROJECT_NAME: string
    VITE_GOLDSKY_MAINNET_SUBGRAPH_VERSION: string
    VITE_GOLDSKY_CALIBRATION_SUBGRAPH_VERSION: string
  }
}
