export const paymentsAbi = [
  {
    type: "function",
    inputs: [
      { name: "token", internalType: "address", type: "address" },
      { name: "to", internalType: "address", type: "address" },
      { name: "amount", internalType: "uint256", type: "uint256" },
    ],
    name: "deposit",
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    inputs: [
      { name: "token", internalType: "address", type: "address" },
      { name: "to", internalType: "address", type: "address" },
      { name: "amount", internalType: "uint256", type: "uint256" },
      { name: "deadline", internalType: "uint256", type: "uint256" },
      { name: "v", internalType: "uint8", type: "uint8" },
      { name: "r", internalType: "bytes32", type: "bytes32" },
      { name: "s", internalType: "bytes32", type: "bytes32" },
    ],
    name: "depositWithPermit",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "token", internalType: "address", type: "address" },
      { name: "to", internalType: "address", type: "address" },
      { name: "amount", internalType: "uint256", type: "uint256" },
      { name: "deadline", internalType: "uint256", type: "uint256" },
      { name: "v", internalType: "uint8", type: "uint8" },
      { name: "r", internalType: "bytes32", type: "bytes32" },
      { name: "s", internalType: "bytes32", type: "bytes32" },
      { name: "operator", internalType: "address", type: "address" },
      { name: "rateAllowance", internalType: "uint256", type: "uint256" },
      { name: "lockupAllowance", internalType: "uint256", type: "uint256" },
      { name: "maxLockupPeriod", internalType: "uint256", type: "uint256" },
    ],
    name: "depositWithPermitAndApproveOperator",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "token", internalType: "address", type: "address" },
      { name: "to", internalType: "address", type: "address" },
      { name: "amount", internalType: "uint256", type: "uint256" },
      { name: "deadline", internalType: "uint256", type: "uint256" },
      { name: "v", internalType: "uint8", type: "uint8" },
      { name: "r", internalType: "bytes32", type: "bytes32" },
      { name: "s", internalType: "bytes32", type: "bytes32" },
      { name: "operator", internalType: "address", type: "address" },
      {
        name: "rateAllowanceIncrease",
        internalType: "uint256",
        type: "uint256",
      },
      {
        name: "lockupAllowanceIncrease",
        internalType: "uint256",
        type: "uint256",
      },
    ],
    name: "depositWithPermitAndIncreaseOperatorApproval",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "token", internalType: "address", type: "address" },
      { name: "operator", internalType: "address", type: "address" },
      {
        name: "rateAllowanceIncrease",
        internalType: "uint256",
        type: "uint256",
      },
      {
        name: "lockupAllowanceIncrease",
        internalType: "uint256",
        type: "uint256",
      },
    ],
    name: "increaseOperatorApproval",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "token", internalType: "address", type: "address" },
      { name: "operator", internalType: "address", type: "address" },
      { name: "approved", internalType: "bool", type: "bool" },
      { name: "rateAllowance", internalType: "uint256", type: "uint256" },
      { name: "lockupAllowance", internalType: "uint256", type: "uint256" },
      { name: "maxLockupPeriod", internalType: "uint256", type: "uint256" },
    ],
    name: "setOperatorApproval",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "railId", internalType: "uint256", type: "uint256" },
      { name: "untilEpoch", internalType: "uint256", type: "uint256" },
    ],
    name: "settleRail",
    outputs: [
      { name: "totalSettledAmount", internalType: "uint256", type: "uint256" },
      { name: "totalNetPayeeAmount", internalType: "uint256", type: "uint256" },
      {
        name: "totalOperatorCommission",
        internalType: "uint256",
        type: "uint256",
      },
      { name: "finalSettledEpoch", internalType: "uint256", type: "uint256" },
      { name: "note", internalType: "string", type: "string" },
    ],
    stateMutability: "payable",
  },
  {
    type: "function",
    inputs: [{ name: "railId", internalType: "uint256", type: "uint256" }],
    name: "terminateRail",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "token", internalType: "address", type: "address" },
      { name: "amount", internalType: "uint256", type: "uint256" },
    ],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "token", internalType: "address", type: "address" },
      { name: "to", internalType: "address", type: "address" },
      { name: "amount", internalType: "uint256", type: "uint256" },
    ],
    name: "withdrawTo",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "token", internalType: "address", type: "address" },
      { name: "owner", internalType: "address", type: "address" },
    ],
    name: "getAccountInfoIfSettled",
    outputs: [
      { name: "fundedUntilEpoch", internalType: "uint256", type: "uint256" },
      { name: "currentFunds", internalType: "uint256", type: "uint256" },
      { name: "availableFunds", internalType: "uint256", type: "uint256" },
      { name: "currentLockupRate", internalType: "uint256", type: "uint256" },
    ],
    stateMutability: "view",
  },
] as const;
