name: Deploy
on:
  push:
    branches: [main]
    paths: ['sites/**']
  workflow_dispatch:
jobs:
  deploy:
    uses: FilOzone/filecoin-nova/.github/workflows/deploy-sites.yml@v0.7.2
    secrets: inherit
